### ISSUE TITLE
PyPi package?

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#17]
#### Summary:
Would like to install this from pip if possible!

**Comment by maedoc** [comment]
this is what I had for pycmdstan
```yml
release_pypi:
  stage: deploy
  image: $registry/$tag
  only:
    - tags
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $TWINE_USERNAME2 -p $TWINE_PASSWORD2 dist/*
```
something similar should be possible with Jenkins or Travis
