### ISSUE TITLE
undefined reference error after installing cmdstan with `install_cmdstan --compiler` on windows gh actions

### ISSUE THREAD

**Issue by teddygroves** [stan-dev/cmdstanpy#722]
#### Summary:

I maintain a Python package that depends on cmdstan via cmdstanpy, and it hit [this error](https://github.com/teddygroves/bibat/actions/runs/7222570483/job/19679805097?pr=70) when running a github action on windows. 

#### Description:

The action that I made installs cmdstan on windows in a fresh environment with the command `install cmdstan --compiler` and runs a simple stan model.

I think this is the most important bit of the error message ([line 800](https://github.com/teddygroves/bibat/actions/runs/7222570483/job/19679805097?pr=70#step:6:801)):

```
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: src/cmdstan/main.o:main.cpp:(.text$_ZN4stan2io15stan_csv_reader12read_samplesERSiRN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEERNS0_15stan_csv_timingEPSo[_ZN4stan2io15stan_csv_reader12read_samplesERSiRN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEERNS0_15stan_csv_timingEPSo]+0x75d): undefined reference to `std::istream::seekg(std::fpos<int>)'
```

The same action went through fine on the ubuntu-latest platform, so I think the problem might have something to do with how cmdstanpy installs cmdstan on windows.

To check that the problem wasn't something to do with the rest of the package, I created a [new repository](https://github.com/teddygroves/cmdstanpy-windows) specifically to test this bug. The new repo contains only a bernoulli stan program and json data input copied from cmdstanpy, a script `script.py` with this code:

```python
import cmdstanpy

model = cmdstanpy.CmdStanModel(stan_file="bernoulli.stan")
mcmc = model.sample(data="bernoulli.data.json")
```

and finally a [github action](https://github.com/teddygroves/cmdstanpy-windows/blob/main/.github/workflows/install-cmdstan-and-run-bernoulli.yml) with these lines:

```yaml
# This workflow tests bibat by using it to make a project, then running the new project's tests.

name: Install cmdstan on windows and run the bernoulli model

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [windows-latest]
            python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install cmdstanpy
      run: pip install cmdstanpy
    - name: Install cmdstan
      run: install_cmdstan --compiler
    - name: Run script
      run: python script.py
```

Running this action led to [a very similar error](https://github.com/teddygroves/cmdstanpy-windows/actions/runs/7223667499/job/19683247641#step:6:244) to the one I started with.

#### Additional Information:

Please let me know if you think this bug belongs more to cmdstan rather than cmdstanpy and I'll move it over!

#### Current Version:

cmdstan version: 2.33.1
cmdstanpy version: 1.2.0
